name: rheator
favicon: null
layout_spectrum: 0.06914
typography_spectrum: 0.12715
title: There is no spoon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8eae9'
    - '#c3c5c4'
    - '#936d48'
    - '#6b4c30'
    - '#432108'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
